name: Build and deploy pkgdown site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install pkgdown
        run: install.packages("pkgdown")
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
