name: Build and deploy pkgdown site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/R
            ~/.local/share/R
            ~/.R
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libfontconfig1-dev \
            libglib2.0-dev \
            libmagick++-dev \
            libcairo2-dev \
            libxt-dev


      - name: Install R packages
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages("devtools")
          install.packages("pkgdown", dependencies = TRUE)
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install local package
        run: devtools::install()
        shell: Rscript {0}

      - name: Build pkgdown site
        run: |
          pkgdown::build_site()
          file.create("docs/.nojekyll")
        shell: Rscript {0}


      - name: Push to GitHub Pages
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/*
          git commit -m 'Update pkgdown site' || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

